name: Auto-approve

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  approve:
    if: github.actor == 'neowalter' && github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr review --approve "${{ github.event.pull_request.number }}"
